# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev-test ]
  pull_request:
    branches: [ dev-test ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      
      # Setup Node.js
    - name: Setup npm package
      run: npm init -y && npm install
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
      # Run stability and tests
    - run: npm ci
    - run: npm run build --if-present
    # - run: npm test
    
      # Setup Forge CLI
    - name: Setup forge cli
      run: npm install -g @forge/cli
    - name: Debug forge version and refuse analytics settings
      run: forge --version & forge settings set usage-analytics false
    - name: Login as Jan Kaiser
      run: forge login -u jan.kaiser@stud.akad.de -t ${{ secrets.FORGE_API_TOKEN }}  # token should be taken from keystore or anything similar
      
      # Deploy to Staging on dev, Production on main. This assumes that the app has already been installed to an Atlassian product.
    - name: Deploy to staging/production
      run: cd nlp-estimate-app & forge deploy -e staging
