# This workflow will install Node, npm, Forge and finally deploy to staging/prod based on the destined branch.

name: Build npm on pull request

on:
  pull_request:
    branches: [ dev, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

        # Set correct environment variable based on branch names with tj-actions/branch-names repository
      - name: Branch Names
        id: branch-name
        uses: tj-actions/branch-names@v5
      - name: Debug current branch name
        run: |
          echo "Running on pr with target: ${{ steps.branch-name.outputs.base_ref_branch }}"
      - name: Set env to staging
        if: endsWith(steps.branch-name.outputs.base_ref_branch, 'dev')
        run: |
          echo "ENVIRONMENT=staging" >> $GITHUB_ENV
      - name: Set env to production
        if: endsWith(steps.branch-name.outputs.base_ref_branch, 'main')
        run: |
          echo "ENVIRONMENT=production" >> $GITHUB_ENV

        # Setup Node.js
      - name: Setup npm package
        run: npm init -y && npm install
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

        # Setup npm and test (no test specified so far)
      - name: Setup npm
        working-directory: ./nlp-estimate-app
        run: npm init -y && npm install
      - name: Run npm CI
        run: npm ci
      - name: Run npm run build --if-present
        run: npm run build --if-present
      #- name: Run npm test
      #  run: npm test
